### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by maboa** [OpenEditor/openeditor#13]
Shortcuts
---

- [x] Play/Pause – `Ctrl+Space` or `Tab`
- [x] Rewind (5 seconds) – `Ctrl+R` or `
- [x] Set playback speed from 0.2x up to 2x – `Ctrl+Alt+1` up to `0`
- [x] Undo – `Ctrl+Z`
- [x] Redo – `Ctrl+Y`

**Comment by Laurian** [comment]
Since when we have highlight and strikethrough in the editor?
